START TRANSACTION;
CREATE DATABASE IF NOT EXISTS base_encurtador;
USE base_encurtador;
CREATE TABLE IF NOT EXISTS `usuarios`(
	`ID_USUARIO` INT PRIMARY KEY AUTO_INCREMENT,
    `NOME` VARCHAR(40) NOT NULL,
    `SOBRENOME`VARCHAR(40) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `TELEFONE` VARCHAR(20),
    `USUARIO` VARCHAR(20) NOT NULL,
    `SENHA` VARCHAR(100) NOT NULL,
    `DATA_ALTERACAO` DATETIME
);
CREATE TABLE IF NOT EXISTS `urls`(
	`ID_URL` INT PRIMARY KEY AUTO_INCREMENT,
    `URL_ORIGINAL` VARCHAR(50) NOT NULL,
    `URL_ENCURTADA` VARCHAR(50) NOT NULL,
    `DATA_OPERACAO` DATETIME NOT NULL,
    `ID_USUARIO` INT NOT NULL,
    FOREIGN KEY(`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
);
INSERT INTO `usuarios`(`NOME`, `SOBRENOME`, `EMAIL`, `TELEFONE`, `USUARIO`, `SENHA`, `DATA_ALTERACAO`)
VALUES('Gabriel', 'Moreira', 'gabrielencurtador@gmail.com', '83999887766', 'gabriel.moreira', '$2a$12$JEFgWjp2wnQz6a9xv1nfmOrEFsKuWzyx2R/4keusFNdgRDjJF0R76', null);
INSERT INTO `usuarios`(`NOME`, `SOBRENOME`, `EMAIL`, `TELEFONE`, `USUARIO`, `SENHA`, `DATA_ALTERACAO`)
VALUES('Diego', 'Moreira', 'diegoencurtador@gmail.com', '83999775544', 'diego.moreira', '$2a$12$ODcGqXSKn25pVUAJIHjyZulhSSSL7/2eo4Ymu4m2rBdlLzEfJVsr2', null);
INSERT INTO `urls`(`URL_ORIGINAL`, `URL_ENCURTADA`, `DATA_OPERACAO`, `ID_USUARIO`)
VALUES('https://google.com.br', 's8mPqX', cast('2021-01-01' as datetime), 1);
INSERT INTO `urls`(`URL_ORIGINAL`, `URL_ENCURTADA`, `DATA_OPERACAO`, `ID_USUARIO`)
VALUES('https://github.com', 'Lq2KRm', cast('2021-01-01' as datetime), 2);
COMMIT;
